/*
 * param_type.h
 *
 *  Created on: 2015年7月23日
 *      Author: guoyj7
 */

#ifndef SMART_KIT_OBJ_DETECTION_PARAM_TYPE_H_
#define SMART_KIT_OBJ_DETECTION_PARAM_TYPE_H_

//todo
#define DETECTION_PARAM_XXX 	1
#define DETECTION_PARAM_XXXX 	2

//ellipse detectio
#define DETECTION_PARAM_ELLIPSE_DETECT_ANGLE 	201
#define DETECTION_PARAM_ELLIPSE_DETECT_INITCENTRE 	202
#define DETECTION_PARAM_ELLIPSE_DETECT_MAXDISFROMINITCENTRE 	203
#define DETECTION_PARAM_ELLIPSE_DETECT_INITB 	204
#define DETECTION_PARAM_ELLIPSE_DETECT_TOLRATIOB 	205
#define DETECTION_PARAM_ELLIPSE_DETECT_MINSCORE 	206
#define DETECTION_PARAM_ELLIPSE_DETECT_MINRELIABILITY 	207

//qrcode detection
#define DETECTION_PARAM_QRCODE_ROI 101
#define DETECTION_PARAM_QRCODE_IMG_BUF 102
#define DETECTION_PARAM_QRCODE_THLD_BUF 103
#define DETECTION_PARAM_QRCODE_MID_ZONE_BUF 104
#define DETECTION_PARAM_QRCODE_SINGLE_OR_MULT 105

//hough foot line detection
#define DETECTION_PARAM_HOUGHFOOT 301
#define DETECTION_PARAM_HOUGHFOOT_ORIENTATION 302


#endif /* SMART_KIT_OBJ_DETECTION_PARAM_TYPE_H_ */
